version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:42
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
     - wordpress_volume:/var/www/html
    restart: always

  mariadb:
    image: mariadb:42
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    expose:
      - "3306"
    container_name: mariadb
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - mariadb_volume:/var/lib/mysql
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    image: wordpress:42
    depends_on:
      - mariadb
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - wordpress_volume:/var/www/html
    restart: always


volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/abbes/data/wordpress
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/abbes/data/mariadb
networks:
  inception:
    driver: bridge
